Numpy
it is a multidimensional array processing package in python

In [2]:
import numpy as np

my_lst=[1,2,3,4,5,6]
arr1=np.array(my_lst)

print(arr1)



[1 2 3 4 5 6]


In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr1.shape

(6,)

In [5]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [6]:
arr1.reshape(2,3)


array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[3,4,5,6,7]

arr2=np.array([my_list1,my_list2,my_list3])
arr2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [9]:
arr2.shape

(3, 5)

In [10]:
#always reshape where total number of elements are same count.. 15 elements can be reshaped as 1*15,3*5,5*3,15*1

Indexing
Accessing array element


In [11]:
arr4=np.array([1,2,3,4,5,6,7,8,9])
print(arr4[3])       

4


In [12]:
arr4[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr4[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
arr4.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]

arr2=np.array([my_list1,my_list2,my_list3])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
print(arr2[0:1,1:3])

[[2 3]]


In [17]:
#print 13,14,15
print(arr2[2: ,2: ])

[[13 14 15]]


In [18]:
#print 8 , 9
print(arr2[1:2,2:4])

[[8 9]]


In [19]:
#arr[row index,column index]

#arr[1:3,2:3]
# [: ,:] means all the rows and columns
#means 1: means index 1 included onwards
#:3 means till index (3-1) 

In [20]:
# get 9,10,14,15
print(arr2[1:,3:])

[[ 9 10]
 [14 15]]


In [21]:
# get 9,10,14,15
print(arr2[1:3,3:5])

[[ 9 10]
 [14 15]]


In [22]:
print(arr2[:1,:])

[[1 2 3 4 5]]


In [23]:
arr5=np.arange(0,19)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [24]:
#np.arnage(start,stop,step)
arr5=np.arange(0,10,step=3)
arr5

array([0, 3, 6, 9])

In [25]:
arr5=np.arange(0,10,step=2)
arr5

array([0, 2, 4, 6, 8])

In [26]:
np.linspace(1,10,num=10)
#start,stop,num is how many no of points
#equally spaced points


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
np.linspace(1,10,num=100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [28]:
#copy function

arr6=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])



print(arr6)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [29]:
arr6[3:]=100
print(arr6)

[  1   2   3 100 100 100 100 100 100 100 100 100 100 100 100]


In [30]:
arr7=arr6

In [31]:
arr7[3:]=500
print(arr7)

[  1   2   3 500 500 500 500 500 500 500 500 500 500 500 500]


In [32]:
print(arr6)

[  1   2   3 500 500 500 500 500 500 500 500 500 500 500 500]


In [33]:
arr7=arr6.copy()
print(arr6)
arr7[3:]= 200
print(arr7)

print(arr6)

[  1   2   3 500 500 500 500 500 500 500 500 500 500 500 500]
[  1   2   3 200 200 200 200 200 200 200 200 200 200 200 200]
[  1   2   3 500 500 500 500 500 500 500 500 500 500 500 500]


In [34]:
# the reference type(the first example (where the value changes in change of other)

# the value type copy() the secpnd example(another memory space created so change in one doesnot impact the other)

# examples are above

In [35]:
#some conditions very useful in exploratory dat analysis
arr8=np.array([1,2,3,4,5,6,7,8,9])
val=2

arr8[arr8 < 5]


array([1, 2, 3, 4])

In [36]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [37]:
arr10=np.arange(0,10).reshape(2,5)
print(arr10)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [38]:
arr11=np.arange(0,10).reshape(2,5)
print(arr11)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [39]:
arr10 * arr11

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [40]:
np.ones(4)
#creates an array of 4 elements with 1

array([1., 1., 1., 1.])

In [41]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
np.ones((5,6),dtype=float)
#5 rows 6 columns

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [43]:
np.random.rand(3,3)
# random number of 3 rows and 3 columns from a random sample of 0 to 1

array([[0.77330017, 0.18228229, 0.67270212],
       [0.59431677, 0.27795687, 0.89320675],
       [0.40589579, 0.22690829, 0.19765807]])

In [44]:
np.random.randn(4,4)
#select the random variable based on standard normal distribution

array([[ 1.00608475, -0.43289359, -0.17378154,  0.181435  ],
       [-0.88290835, -0.88573321, -1.69233481,  0.25998782],
       [-0.66186135,  0.00389376, -1.87355834, -0.84300509],
       [ 0.83316369, -0.99915453, -0.16377456,  0.54646574]])

In [46]:

import pandas as pd

In [47]:
np.random.randint(0,100,8).reshape(4,2)
#randint(low,high,how many numbers)
#4 rows 2 columns

array([[ 5, 75],
       [66, 92],
       [87, 21],
       [56, 36]])

In [48]:
np.random.random_sample((2,5))
# sample is from 0.0 to 1.0
# 2 rows 5 columns

array([[0.25884768, 0.25008902, 0.98061391, 0.80139576, 0.72003717],
       [0.90290152, 0.7162891 , 0.20837267, 0.20402249, 0.65367617]])